//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabateur
{
    using System;
    
    [Flags]
    public enum BlockType : int
    {
        Cart = 1,
        Pickaxe = 2,
        Lantern = 4
    }
}
