//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabateur
{
    using System;
    
    public enum CardType : int
    {
        Path = 0,
        Block = 1,
        Map = 2,
        RemovePath = 3,
        AntiBlock = 4,
        GoalPath = 5
    }
}
