//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabateur
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardSet
    {
        public int Id { get; set; }
        public CardType Type { get; set; }
        public string Owner { get; set; }
        public Nullable<BlockType> BlockType { get; set; }
        public Nullable<Direction> PathOpenings { get; set; }
        public Nullable<Direction> Path { get; set; }
        public Nullable<int> FieldCol { get; set; }
        public Nullable<int> FieldRow { get; set; }
        public Nullable<bool> IsPathUpside { get; set; }
    
        public virtual PlayerSet PlayerSet { get; set; }
    }
}
