//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabateur
{
    using System;
    
    public enum CardStatus : int
    {
        InDeck = 0,
        OnField = 1,
        Discarded = 2,
        InHand = 3
    }
}
