//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabateur
{
    using System;
    
    [Flags]
    public enum Direction : int
    {
        Up = 1,
        Down = 2,
        Left = 4,
        Right = 8
    }
}
